### PR TITLE
fix: blossom parsing issues

### LINKED ISSUE #120: Blossom blob upload fails
Blossom uploads are failing with error `type 'String' is not a subtype of type 'int?'` 

This is because `BlobNip94` has values which are not strings, all values must be strings

https://github.com/relaystr/ndk/blob/8897201eafa0d5de43a3686796943ddfb9c971e8/packages/ndk/lib/domain_layer/entities/blossom_blobs.dart#L172

### PR DESCRIPTION
**Pull request by 1-leo**
fixes #120

### CODE REVIEW

File: packages/ndk/lib/domain_layer/entities/blossom_blobs.dart [hunk 1]
```diff
@@ -169,7 +179,8 @@ class BlobNip94 {
       mimeType: json['m'] ?? '',
       sha256: json['x'] ?? '',
       originalsha256: json['ox'] ?? '',
-      size: json['size'] ?? 0,
+      // parse int from string
+      size: _parseSize(json['size']),
       dimenssions: json['dim'],
```
Comment (v0l) [inline packages/ndk/lib/domain_layer/entities/blossom_blobs.dart:184]: You need to test this too the format is a string `"1920x1080"`  it wont be parsed into `int?`

Comment (leo-lox) [reply packages/ndk/lib/domain_layer/entities/blossom_blobs.dart:184]: according to the specs its used for file byte size, is this used differently in implementations that exists?

Comment (v0l) [reply packages/ndk/lib/domain_layer/entities/blossom_blobs.dart:184]: No i mean `dim` tag not `size`

Comment (leo-lox) [reply packages/ndk/lib/domain_layer/entities/blossom_blobs.dart]: got it

File: packages/ndk/test/entities/blob_nip94_test.dart [hunk 2]
```diff
@@ -55,5 +55,36 @@ void main() async {
...
+      };
+
+      final Map<String, dynamic> malformedJson2 = {
+        "url": '',
+        "sha256": '',
+        "size": "512",
+        "dim": 100,
+        "type": "notype",
+        "nip94": {
+          "dim": 100,
```
Comment (v0l) [inline packages/ndk/test/entities/blob_nip94_test.dart:79]: Why handle this? `dim 100` is invalid

Comment (v0l) [reply packages/ndk/test/entities/blob_nip94_test.dart:79]: Ok i thought you added this because one server IS responding like this
