### PR TITLE
fix: preserve tags and custom fields in metadata

### LINKED ISSUE #438: metadata does not store tags/custom content fields
**Describe the bug**
Metadata object does not store tags or custom content:
```
  /// convert to nip01 event
  Nip01Event toEvent() {
    return Nip01Event(
        pubKey: pubKey,
        content: jsonEncode(toJson()),
        kind: kKind,
        tags: [],
        createdAt: updatedAt ?? 0);
  }
```

Is it impossible to use the metadata usecase to fetch profiles that store other content fields?
Say if I want a custom field or tag on the metadata event, and I want to use NDKs caching mechanism for metadata, I suppose that's impossible.

Until recently, https://github.com/nostr-protocol/nips/pull/2216, NIP-39 allowed us to store external identities on "i" tags on metadata, but using NDKs metadata functionality strip that information. 

Are there any plans to store the raw/complete metadata or will it always be the stripped down version?

### PR DESCRIPTION
**Pull request by nogringo**
- Add tags field to Metadata entity
  - Add rawContent field to preserve original JSON
  - Update fromEvent() to store tags and rawContent
  - Update toEvent() to merge with original JSON
  - Add helper methods setCustomField() and getCustomField()
  - Fix constructor to use mutable list for tags

  Fixes #438

### CODE REVIEW

File: packages/ndk/lib/domain_layer/entities/metadata.dart [hunk 1]
```diff
@@ -45,20 +57,38 @@ class Metadata {
...
+    String? nip05,
+    String? lud16,
+    String? lud06,
+    this.updatedAt,
+    this.refreshedTimestamp,
+    List<List<String>>? tags,
+    Map<String, dynamic>? content,
+  })  : tags = tags ?? [],
+        content = content ?? {} {
+    // Initialize content with provided known fields
```
Comment (frnandu) [inline packages/ndk/lib/domain_layer/entities/metadata.dart]: If both content and individual fields (like name) are passed, the individual fields overwrite content values. This behavior should be documented.

**Comment by 1-leo** [comment]
ping @frnandu
